apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  generation: 1
  labels:
    kubevirt.io/os: linux
    taloscluster: taloscp
  name: taloscp
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: vm1
    spec:
      domain:
        cpu:
          cores: 4
        devices:
          disks:
          - bootOrder: 2
            cdrom:
              bus: sata
            name: cdromiso
          - disk:
              bus: virtio
            name: harddrive
            bootOrder: 1
        machine:
          type: q35
        resources:
          requests:
            memory: 8192M
      volumes:
      - name: cdromiso
        persistentVolumeClaim:
          claimName: talos
      - name: harddrive
        persistentVolumeClaim:
          claimName: taloshd
